### ISSUE TITLE
Install alabaster as a dependency

### ISSUE THREAD

**Issue by willingc** [jupyterhub/alabaster-jupyterhub#4]
It looks like alabaster is not yet installed as a dependency. @choldgraf, you may wish to doublecheck flit and setup.py to see what I missed. At a conference today. Thanks.

**Comment by choldgraf** [comment]
Hmm, it wasn't in the pyproject.yoml file, maybe that's where the dependency lives (added in #5 ). It's listed in `setup.py` and `dev-requirements.txt`. I'm still pretty unknowledgeable about exactly which pieces of metadata map on to what parts of the installation process :-/

**Comment by willingc** [comment]
I think PR #6 takes care of this. Let's merge this one before #5

**Comment by choldgraf** [comment]
I think this is now taken care of, so closing!
